/**
 * Public PayPal configuration for the online donation.
 *
 * ---------------------------------------------------------------------------
 * WHAT IS IN THIS FILE
 * ---------------------------------------------------------------------------
 * These are **public PayPal hosted-button identifiers**. A hosted-button id, a
 * hosted-button client id and a PayPal.me-style payment link are all designed
 * to be readable by every visitor — they are embedded in the page the browser
 * downloads, and they cannot be otherwise.
 *
 * **No private API secret is present, and none may ever be added here.** A
 * PayPal REST secret, an access token or a webhook signing key would be
 * inlined into the bundle by Vite and published to the world. If server-side
 * PayPal work is ever needed, it belongs on a server, behind a variable
 * without the `VITE_` prefix — see `.env.example`.
 *
 * ---------------------------------------------------------------------------
 * WHO RECEIVES THE MONEY
 * ---------------------------------------------------------------------------
 * **Fundación Unidos por un Acuerdo Social — FUNUDOS** receives the donation.
 * **Fundación Alborada** is the public project that FUNUDOS administers. The
 * donation section states this to the visitor; it is not left implicit.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS SITE DOES NOT DO
 * ---------------------------------------------------------------------------
 * PayPal hosts and processes the payment in full. This site does not collect
 * card details or PayPal credentials, does not create orders, does not store
 * payment information, and never displays a success state of its own — only
 * PayPal can tell a donor that a payment completed.
 *
 * Values here were generated by the PayPal hosted-button builder for the
 * foundation's own account. Do not change them without saying so explicitly.
 */

/** Fallback: PayPal's own hosted payment page. Works without any script. */
export const PAYPAL_DONATION_URL =
  "https://www.paypal.com/ncp/payment/K79TU3UFVP5J2";

/** The hosted button configured in the foundation's PayPal account. */
export const PAYPAL_HOSTED_BUTTON_ID = "FX3C3ZF9BZUNY";

/** Public client id issued for the hosted-buttons component. Not a secret. */
export const PAYPAL_CLIENT_ID =
  "BAAorzAsCfDAHufEiN4IewvM_2d2BZEJRV9TztNJcuG-VrINZMjR8ng7l2lFh0uUDXqzha6RSDCitER3K4";

/**
 * The only origin this integration is allowed to load a script from.
 * Asserted by `payments.test.ts`, so a typo or a substituted host fails the
 * suite rather than shipping.
 */
export const PAYPAL_SDK_ORIGIN = "https://www.paypal.com";

/** Query parameters exactly as the PayPal button builder produced them. */
export const PAYPAL_SDK_PARAMS = {
  "client-id": PAYPAL_CLIENT_ID,
  components: "hosted-buttons",
  "disable-funding": "venmo",
  currency: "USD",
} as const;

/**
 * Builds the SDK URL from the parts above.
 *
 * Built rather than pasted so the identifiers exist once. `URL` also
 * guarantees the result is a well-formed absolute HTTPS URL, which a
 * hand-concatenated string does not.
 */
export function paypalSdkUrl(): string {
  const url = new URL("/sdk/js", PAYPAL_SDK_ORIGIN);
  for (const [key, value] of Object.entries(PAYPAL_SDK_PARAMS)) {
    url.searchParams.set(key, value);
  }
  return url.toString();
}

export const PAYPAL_SDK_URL = paypalSdkUrl();
